# Generated by Django 6.0.1 on 2026-01-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='specialization',
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='lawyers/'),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='bar_council_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
    ]
