# Generated by Django 6.0.1 on 2026-01-13 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_lawyerprofile_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='subject',
            field=models.CharField(default='Initial request', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.servicecategory'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
