# Generated by Django 6.0 on 2026-01-14 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_consultationrequest_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='room_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.servicecategory'),
        ),
    ]
