# Generated by Django 6.0.1 on 2026-01-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_wallet_updated_at_alter_wallet_user_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
