# Generated by Django 6.0.1 on 2026-01-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_consultationrequest_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
