# Generated by Django 6.0 on 2026-05-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_lawyerprofile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='ai_client_checklist',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='ai_refined_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='estimated_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
