# Generated by Django 6.0 on 2026-05-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_consultationrequest_ai_client_checklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='ai_call_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='ai_drafted_document',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='ai_execution_plan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='call_transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='case_milestone',
            field=models.CharField(default='Pending Consultation', max_length=100),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='current_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='desired_outcome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='case_docs/'),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='issue_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='opposing_party',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
