# Generated by Django 6.0.1 on 2026-06-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_consultationrequest_ai_call_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='transcript_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
